name: Checkout Pull Request Code and Install npm

on:
  pull_request:
    branches:
      - main

jobs:
  checkout_and_install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout pull request code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.2' # or specify the version you need

      - name: Install npm dependencies
        run: npm install

      - name: Install SFDX
        run: npm install @salesforce/cli --global

      - name: SFDX version
        run: sfdx -v

      - name: Display Authenticated Org
        run: sfdx force:org:list

      - name: Access Repository Secret and create server.key
        run:  echo "${{ env.SERVER_KEY }}" | base64 --decode > server.key
        #run:  echo "${{ secrets.SALESFORCE_SERVER_KEY }}" | base64 --decode > server.key

      - name: cat server.key
        run:  cat server.key

      - name: Authenticated devOrg
        run: sf org login jwt --client-id ${{ secrets.SALESFORCE_CLIENT_ID }} --jwt-key-file server.key  --username ${{ secrets.SALESFORCE_USERNAME }} --instance-url https://amolm-dev-ed.my.salesforce.com -a devorg
      
      - name: Display Authenticated Org
        run: sfdx force:org:list          