name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'
      release_folder:
        description: 'Release folder name'
        required: true
        default: 'release'
      environment:
          description: 'Environment to deploy to'
          required: true
          default: 'dev'
          options:
            - dev
            - staging
            - prod        

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    #  - name: Checkout pull request code
    #    uses: actions/checkout@v2
    #    with:
    #      ref: ${{ github.event.inputs.branch }}

      - name: output variables
        run: |
            # Get the pull request branch name
            branch_name=$(echo "${{ github.event.inputs.branch }}")
            release_folder=$(echo "${{ github.event.inputs.release_folder }}")
            echo "${{ github.event.inputs.branch }}" 
            echo "${{ github.event.inputs.release_folder }}"
            echo "branch_name: $branch_name" 
            echo "release_folder: $release_folder"

            next_saturday=$(date -d "next Saturday" "+%Y-%m-%d")
            previous_saturday=$(date -d "last Saturday" "+%Y-%m-%d")
            date -d "next Saturday" "+%Y-%m-%d"
            date -d "last Saturday" "+%Y-%m-%d"
            release_name = echo "release-"+$next_saturday
            previous_saturday=$(date -d "last Saturday" "+%Y-%m-%d")
            if [ -d "/home/runner/work/sdf/" ]; then
              echo "Folder exists $next_saturday"
            else
              echo "Folder does not exist $previous_saturday"
            fi
            echo "release name = $release_name"
