name: Validate pull request

on:
  pull_request:
    branches:
      - main

jobs:
  validate_PR_2:
    runs-on: ubuntu-latest

    steps:
      - name: get next saturday 
        run: |
              date1="30-AUG-2015"
              date -d "$date1 next saturday"
