name: Validate pull request

on:
  pull_request:
    branches:
      - main

jobs:
  validate_PR_2:
    runs-on: ubuntu-latest

    steps:
      - name: get next saturday 
        run: |
              date -d "next Saturday" "+%Y-%m-%d"
