
name: Validate pull request

on:
  pull_request:
    branches:
      - main

jobs:
  validate_PR_2:
    runs-on: ubuntu-latest

    steps:
      - name: get next saturday 
        run: |
              #next = $( date -d "next Saturday" "+%Y-%m-%d" )
              #previous = $(date -d "last Saturday" "+%Y-%m-%d")
              date -d "next Saturday" "+%Y-%m-%d"
              date -d "last Saturday" "+%Y-%m-%d"
              if [ -d "/home/runner/work/sfdc/" ]; then
                echo "Folder exists"
              else
                echo "Folder does not exist "
              fi

